name: Publish
on:
  push:
    tags:
      - v*.*.* # run on version tags, e.g. v2.0.0
jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Powershell
        run: |
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https software-properties-common
            wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update
            sudo add-apt-repository -y universe
            sudo apt-get install -y powershell

  build:
    name: Publish
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Get version
        id: get_version
        shell: pwsh
        run: |
          $version=($env:GITHUB_REF -Split '/')[-1]
          Write-Output "::set-output name=version::$version"
    
      - name: Send to pkg.go.dev
        shell: pwsh
        run: |
            ./tools.ps1 publish ${{ steps.get_version.outputs.version }}
